### ISSUE TITLE
String with '-' or space doesn't work

### ISSUE THREAD

**Issue by johnwyz88** [mysto/java-fpe#1]
For example, all of these fails to be encrypted.

    @Param({
        "driver licences 123456-789",
        "ssn 841-01-2233",
        "cc 5360888786433111",
        "cell +1(416)-562-0165",
        "email donald.duck@google.com",
        "large json event",
    })

java.lang.NumberFormatException: For input string: "c 5360"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.math.BigInteger.<init>(BigInteger.java:543)
	at com.amazon.awsstewardengine.FF3Cipher.encrypt(FF3Cipher.java:95)

java.lang.NumberFormatException: Illegal embedded sign character
	at java.base/java.math.BigInteger.<init>(BigInteger.java:492)
	at com.amazon.awsstewardengine.FF3Cipher.encrypt(FF3Cipher.java:95)

**Comment by bschoening** [comment]
Yes, it is correct that only numeric and mono-case US ASCII letters are supported (a-z).  The NIST FPE Feistel cipher has a 'radix' representing the range of characters:  As mentioned in the Readme.md, "Java's standard library's BigInteger supports radices/bases up to 36. Therefore, this package supports a max base of 36, which can contain numeric digits 0-9 and alphabetic characters a-z."

Due to this radix limitation, special characters, or international characters are not supported.  I would suggest you remove the formatting (dashes, spaces) before encryption, and re-apply formatting afterwards.
